<%

if ENV["USER"] == "jenkins"
  formatter = "progress"
  keep_sim_open_after = "0"
else
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "1"
end

%>

verbose: DEBUG=1
common: -f <%= formatter %>

app:           APP="../LPTestTarget.app"
bundle_id:     BUNDLE_ID=com.xamarin.LPTestTarget

simulator:     -p app -p common NO_STOP=<%= keep_sim_open_after %>
default:       -p simulator
